# Generated by Django 5.1.2 on 2024-11-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcoverpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=170),
        ),
    ]
